# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'NSThread_GCD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NSThread_GCD
  pod 'WCDB'


end
